services:
    mealie:
        image: ghcr.io/mealie-recipes/mealie:latest
        container_name: mealie
        restart: unless-stopped
        ports:
            - 4448:9000
        environment:
            - TZ=Europe/Zurich
            - PUID=0
            - PGID=0
            - ALLOW_SIGNUP=false
            - BASE_URL=https://cook.example.com
            - SECURITY_MAX_LOGIN_ATTEMPTS=10
            - DEFAULT_GROUP=home
        volumes:
            - ./data:/app/data

# Default credentials
# Username: changeme@example.com
# Password: MyPassword
