version: "3"
services:
  vaultwarden:
    image: vaultwarden/server
    container_name: vaultwarden
    ports:
      - 8080:80
    volumes:
      - ./data:/data
    restart: 'unless-stopped'
    environment:
      - ADMIN_TOKEN=TOKEN
      - SIGNUPS_ALLOWED=false
