version: '3.1'

services:
  ghost:
    image: ghost:5-alpine
    restart: unless-stopped
    ports:
      - 2368:2368
    environment:
      database__client: mysql
      database__connection__host: db
      database__connection__user: root
      database__connection__password: ghost
      database__connection__database: ghost
      url: https://example.com
    volumes:
      - ./data:/var/lib/ghost/content
    depends_on:
      - db

  db:
    image: mysql:8.0
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ghost
    volumes:
      - ./db:/var/lib/mysql

